//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceTable
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public System.DateTime FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public int MinQty { get; set; }
        public decimal Price { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual ItemGroups ItemGroups { get; set; }
        public virtual Items Items { get; set; }
    }
}
