//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    public partial class SalesDBEntities : DbContext
    {
        public SalesDBEntities()
            : base("name=SalesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        [DbFunction("SalesDb.dbo", "getPrice")]
        public string YourScalarFunction(int itemId, int customerId, decimal qty, DateTime date  )
        {
            var lObjectContext = ((IObjectContextAdapter)this).ObjectContext;

            return lObjectContext.
                CreateQuery<string>(
                    "SalesDb.dbo.getPrice", new ObjectParameter[]{
                new ObjectParameter("itemId", itemId),
                new ObjectParameter("customerId", customerId),
                new ObjectParameter("qty", qty),
                new ObjectParameter("date", date)
                }).
                Execute(MergeOption.NoTracking).
                FirstOrDefault();
        }

        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<ItemGroups> ItemGroups { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<PaymentAgreements> PaymentAgreements { get; set; }
        public virtual DbSet<PaymentTable> PaymentTable { get; set; }
        public virtual DbSet<PriceTable> PriceTable { get; set; }
        public virtual DbSet<SalesLine> SalesLine { get; set; }
        public virtual DbSet<SalesTable> SalesTable { get; set; }
    }
}
